name: 'Docker Hub Description'
author: 'Peter Evans'
description: 'An action to update a Docker Hub repository description from README.md'
runs:
  using: 'docker'
  image: 'docker://mjenz/dockerhub-description'
branding:
  icon: 'upload'
  color: 'blue'
